// Mock data fallback — used when Fake Store API is unreachable

export const MOCK_PRODUCTS = [
  {
    id: 1,
    title: "Apple MacBook Pro 14\" M3 Chip",
    price: 1999.99,
    description: "Apple MacBook Pro with M3 chip delivers extraordinary performance for professionals. Features a stunning Liquid Retina XDR display, up to 22 hours of battery life, and the power to handle the most demanding workflows.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80",
    rating: { rate: 4.9, count: 3200 },
  },
  {
    id: 2,
    title: "Sony WH-1000XM5 Wireless Headphones",
    price: 349.99,
    description: "Industry-leading noise canceling with Dual Noise Sensor technology. Up to 30-hour battery life, touch sensor controls, and premium sound quality.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
    rating: { rate: 4.8, count: 1850 },
  },
  {
    id: 3,
    title: "Samsung 4K OLED Smart TV 55\"",
    price: 1299.00,
    description: "Experience breathtaking picture quality with Samsung's OLED panel. Smart TV features, HDR10+, and Dolby Atmos sound make this the centerpiece of any living room.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f4834f?w=400&q=80",
    rating: { rate: 4.7, count: 980 },
  },
  {
    id: 4,
    title: "iPhone 15 Pro Max 256GB",
    price: 1199.00,
    description: "iPhone 15 Pro Max with titanium design, A17 Pro chip, 48MP main camera with 5x telephoto zoom, and Action Button for customizable shortcuts.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&q=80",
    rating: { rate: 4.8, count: 5100 },
  },
  {
    id: 5,
    title: "Canon EOS R6 Mark II Mirrorless Camera",
    price: 2499.00,
    description: "Professional mirrorless camera with 40fps burst shooting, advanced subject recognition AF, and 6K RAW video. Perfect for photographers and videographers.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&q=80",
    rating: { rate: 4.9, count: 420 },
  },
  {
    id: 6,
    title: "iPad Pro 12.9\" M2 Wi-Fi 256GB",
    price: 1099.00,
    description: "The ultimate iPad experience with M2 chip, stunning Liquid Retina XDR display, Apple Pencil support, and all-day battery life.",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400&q=80",
    rating: { rate: 4.8, count: 1200 },
  },
  {
    id: 7,
    title: "Men's Premium Slim Fit Blazer",
    price: 149.99,
    description: "Sophisticated slim-fit blazer crafted from premium wool blend. Perfect for business meetings or evening events. Available in multiple colors.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80",
    rating: { rate: 4.4, count: 620 },
  },
  {
    id: 8,
    title: "Men's Classic Leather Jacket",
    price: 299.00,
    description: "Genuine leather jacket with a timeless design. Features quilted lining, multiple pockets, and a durable YKK zipper. A wardrobe essential.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80",
    rating: { rate: 4.6, count: 890 },
  },
  {
    id: 9,
    title: "Men's Casual Linen Shirt",
    price: 59.99,
    description: "Breathable linen shirt perfect for warm weather. Features a relaxed fit, button-down collar, and is available in a range of summer colors.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80",
    rating: { rate: 4.3, count: 440 },
  },
  {
    id: 10,
    title: "Men's Running Sneakers Pro",
    price: 129.99,
    description: "High-performance running shoes with responsive cushioning, breathable mesh upper, and durable rubber outsole. Built for speed and comfort.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    rating: { rate: 4.5, count: 1320 },
  },
  {
    id: 11,
    title: "Women's Floral Summer Dress",
    price: 89.99,
    description: "Elegant floral print midi dress with a flattering A-line silhouette. Made from lightweight chiffon, perfect for summer occasions.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80",
    rating: { rate: 4.6, count: 780 },
  },
  {
    id: 12,
    title: "Women's Trench Coat – Beige",
    price: 199.99,
    description: "Classic double-breasted trench coat in premium cotton-gabardine. Timeless style with storm flaps, adjustable belt, and deep pockets.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1548369937-47519962c11a?w=400&q=80",
    rating: { rate: 4.7, count: 560 },
  },
  {
    id: 13,
    title: "Women's High-Waist Yoga Pants",
    price: 74.99,
    description: "Premium four-way stretch fabric yoga pants with high-waist design, hidden pocket, and moisture-wicking technology for all-day comfort.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&q=80",
    rating: { rate: 4.5, count: 1100 },
  },
  {
    id: 14,
    title: "Women's Silk Blouse – Navy",
    price: 119.00,
    description: "Luxurious 100% silk blouse with a relaxed fit and elegant drape. Features a V-neck, button placket, and side slits for a refined look.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=400&q=80",
    rating: { rate: 4.4, count: 330 },
  },
  {
    id: 15,
    title: "Diamond Solitaire Pendant Necklace",
    price: 599.00,
    description: "Stunning 0.5ct round diamond pendant set in 18k white gold. Comes with an 18-inch cable chain and luxury gift box. GIA certified.",
    category: "jewelery",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&q=80",
    rating: { rate: 4.9, count: 290 },
  },
  {
    id: 16,
    title: "Gold Layered Chain Bracelet Set",
    price: 89.99,
    description: "Elegant set of three 18k gold-plated layered bracelets. Features delicate chains with charm accents, adjustable sizing, and tarnish-resistant finish.",
    category: "jewelery",
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&q=80",
    rating: { rate: 4.6, count: 510 },
  },
  {
    id: 17,
    title: "Rose Gold Sapphire Ring",
    price: 349.00,
    description: "Stunning blue sapphire ring in 14k rose gold setting with micro-pavé diamond halo. A timeless piece that makes the perfect gift.",
    category: "jewelery",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&q=80",
    rating: { rate: 4.8, count: 185 },
  },
  {
    id: 18,
    title: "Pearl Drop Earrings – Classic White",
    price: 129.00,
    description: "Freshwater pearl drop earrings with 18k gold-filled hooks. 9-10mm pearls with AAA luster rating. Hypoallergenic and nickel-free.",
    category: "jewelery",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&q=80",
    rating: { rate: 4.7, count: 420 },
  },
  // ── More Men's Clothing ──────────────────────────────────────────
  {
    id: 19,
    title: "Men's Slim Chino Pants – Khaki",
    price: 79.99,
    description: "Classic slim-fit chino trousers in stretch cotton blend. Features a flat-front silhouette, zip-fly, and a versatile khaki colorway that pairs with everything.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80",
    rating: { rate: 4.4, count: 730 },
  },
  {
    id: 20,
    title: "Men's Graphic Oversized Hoodie",
    price: 89.99,
    description: "Ultra-soft heavyweight fleece hoodie with a bold graphic print. Features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80",
    rating: { rate: 4.5, count: 985 },
  },
  {
    id: 21,
    title: "Men's Denim Jacket – Washed Blue",
    price: 119.99,
    description: "Timeless denim jacket in a washed blue finish with a relaxed fit. Chest pockets, button-front closure, and adjustable waist tabs for a classic look.",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80",
    rating: { rate: 4.6, count: 572 },
  },
  // ── More Women's Clothing ─────────────────────────────────────────
  {
    id: 22,
    title: "Women's Cropped Denim Jacket",
    price: 109.99,
    description: "Chic cropped denim jacket with raw-hem details, chest pockets, and a flattering fitted silhouette. Pairs effortlessly with dresses or high-waist jeans.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=400&q=80",
    rating: { rate: 4.5, count: 640 },
  },
  {
    id: 23,
    title: "Women's Oversized Knit Sweater",
    price: 94.99,
    description: "Cozy oversized ribbed-knit sweater in a chunky weave. Features dropped shoulders, wide sleeves, and a relaxed hem — perfect for layering in cooler months.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=80",
    rating: { rate: 4.7, count: 810 },
  },
  {
    id: 24,
    title: "Women's High-Waist Wide-Leg Jeans",
    price: 119.00,
    description: "Flattering high-waist wide-leg jeans crafted from premium stretch denim. Features a button-fly, five-pocket design, and a clean indigo wash.",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&q=80",
    rating: { rate: 4.6, count: 920 },
  },
  // ── Home Category ─────────────────────────────────────────────────
  {
    id: 25,
    title: "Minimalist Ceramic Table Lamp",
    price: 89.99,
    description: "Elegant ceramic base table lamp with a linen shade. Soft warm-white illumination creates the perfect ambient glow in any living space. Includes LED bulb.",
    category: "home",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80",
    rating: { rate: 4.6, count: 480 },
  },
  {
    id: 26,
    title: "Premium Cotton Bedding Set – White",
    price: 159.99,
    description: "400 thread-count Egyptian cotton bedding set including duvet cover and two pillowcases. Buttery-soft, breathable, and hotel-quality comfort every night.",
    category: "home",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&q=80",
    rating: { rate: 4.8, count: 1230 },
  },
  {
    id: 27,
    title: "Scented Soy Candle Set – Lavender & Vanilla",
    price: 45.99,
    description: "Hand-poured soy wax candles in a set of three — lavender, vanilla, and cedarwood. Up to 50 hours of burn time each with lead-free cotton wicks.",
    category: "home",
    image: "https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=400&q=80",
    rating: { rate: 4.7, count: 870 },
  },
  {
    id: 28,
    title: "Boho Macramé Wall Hanging",
    price: 64.99,
    description: "Handcrafted boho macramé wall hanging made from natural cotton rope. Adds texture and warmth to any bedroom or living room. Measures 24\" x 36\".",
    category: "home",
    image: "https://images.unsplash.com/photo-1522444195799-478538b28823?w=400&q=80",
    rating: { rate: 4.5, count: 340 },
  },
  {
    id: 29,
    title: "Wooden Serving Tray & Coaster Set",
    price: 54.99,
    description: "Handcrafted acacia wood serving tray paired with a matching set of four coasters. Food-safe oil finish, natural grain patterns — no two pieces alike.",
    category: "home",
    image: "https://images.unsplash.com/photo-1584269600957-9c3bedb5d607?w=400&q=80",
    rating: { rate: 4.6, count: 290 },
  },
  {
    id: 30,
    title: "Indoor Monstera Deliciosa Plant",
    price: 39.99,
    description: "Popular Swiss Cheese Monstera in a 6\" terracotta pot. Low maintenance, air purifying, and a striking addition to shelves, desks, or living rooms.",
    category: "home",
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=400&q=80",
    rating: { rate: 4.8, count: 1560 },
  },
  {
    id: 31,
    title: "Stainless Steel French Press Coffee Maker",
    price: 49.99,
    description: "34oz double-walled stainless steel French press. Keeps coffee hot for 4 hours, brews rich and full-bodied coffee in 4 minutes. Dishwasher safe.",
    category: "home",
    image: "https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?w=400&q=80",
    rating: { rate: 4.7, count: 2100 },
  },
  {
    id: 32,
    title: "Velvet Throw Pillow Set – Dusty Rose",
    price: 34.99,
    description: "Set of two luxurious velvet cushion covers in dusty rose with hidden zipper. 18\"x18\" size, compatible with standard pillow inserts. Machine washable.",
    category: "home",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
    rating: { rate: 4.5, count: 670 },
  },
];

export const MOCK_CATEGORIES = [
  "electronics",
  "men's clothing",
  "women's clothing",
  "jewelery",
  "home",
];
